play.http.secret.key="<YOUR_SECRET_KEY>"

# Cấu hình kết nối Database (Cassandra)
db.janusgraph {
  storage {
    backend = cql
    hostname = ["cassandra"]
    cql {
      cluster-name = thp
      keyspace = thehive
    }
  }
}

# Cấu hình kết nối Indexing (Elasticsearch)
index.search {
  backend = elasticsearch
  hostname = ["http://elasticsearch:9200"]
  index-name = thehive
}