play.http.secret.key="btwHlh0JnCqKPYPF8rDM9UtEoB5aVDwtHQXHzVk3I5qArbcmKoKaUb8x5l2q5cqX"

db.janusgraph {
  storage {
    backend = cql
    hostname = ["cassandra"]
    cql {
      cluster-name = thp
      keyspace = thehive
    }
  }
}

index.search {
  backend = elasticsearch
  hostname = ["http://elasticsearch:9200"]
  index-name = thehive
}